//
//  MonitorModels.swift
//  GitHubNotifierCore
//
//  Created by X on 5/21/26.
//

import Foundation

/// The target of a monitor, indicating what GitHub resource to monitor.
public enum MonitorTarget: Codable, Equatable, Sendable {
    case account(login: String)
    case repository(owner: String, name: String)
    case search(query: String, name: String)
    case code(query: String, name: String)

    public var idString: String {
        switch self {
        case let .account(login):
            "account:\(login.lowercased())"
        case let .repository(owner, name):
            "repo:\(owner.lowercased())/\(name.lowercased())"
        case let .search(query, _):
            "search:\(query)"
        case let .code(query, _):
            "code:\(query)"
        }
    }

    public var displayName: String {
        switch self {
        case let .account(login):
            "@\(login)"
        case let .repository(owner, name):
            "\(owner)/\(name)"
        case let .search(_, name):
            name
        case let .code(query, name):
            "\(name) (Keyword: \(query))"
        }
    }
}

/// Defines a specific monitor item created by the user.
public struct MonitorDefinition: Codable, Identifiable, Equatable, Sendable {
    public let id: UUID
    public let target: MonitorTarget
    public var isEnabled: Bool
    /// Toggle configuration for specific event kinds (e.g. pr, issue, commit, follow)
    public var eventToggles: [String: Bool]

    public init(id: UUID = UUID(), target: MonitorTarget, isEnabled: Bool = true, eventToggles: [String: Bool] = [:]) {
        self.id = id
        self.target = target
        self.isEnabled = isEnabled
        self.eventToggles = eventToggles
    }
}

/// A localized event generated by a monitor.
public struct MonitorEvent: Codable, Identifiable, Equatable, Sendable {
    public let id: String // Stable unique ID to prevent duplicates
    public let kind: String // "commit", "issue", "pr", "release", "follow", "code_match"
    public let targetId: UUID // The definition ID that triggered this event
    public let actor: String
    public let repo: String
    public let title: String
    public let url: String
    public let occurredAt: Date
    public var isRead: Bool

    public init(
        id: String,
        kind: String,
        targetId: UUID,
        actor: String,
        repo: String,
        title: String,
        url: String,
        occurredAt: Date,
        isRead: Bool = false
    ) {
        self.id = id
        self.kind = kind
        self.targetId = targetId
        self.actor = actor
        self.repo = repo
        self.title = title
        self.url = url
        self.occurredAt = occurredAt
        self.isRead = isRead
    }
}

extension MonitorTarget {
    public static func parse(input: String, type: String, name: String = "") -> MonitorTarget? {
        let clean = input.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !clean.isEmpty else { return nil }

        // Handle full URLs
        if clean.lowercased().hasPrefix("http://") || clean.lowercased().hasPrefix("https://") {
            guard let url = URL(string: clean),
                  let host = url.host,
                  host.contains("github.com") else {
                return nil
            }
            let pathComponents = url.pathComponents.filter { $0 != "/" && !$0.isEmpty }
            if pathComponents.count == 1 {
                return .account(login: pathComponents[0])
            } else if pathComponents.count >= 2 {
                return .repository(owner: pathComponents[0], name: pathComponents[1])
            }
            return nil
        }

        switch type {
        case "account":
            let login = clean.hasPrefix("@") ? String(clean.dropFirst()) : clean
            return .account(login: login)
        case "repository":
            let parts = clean.split(separator: "/")
            if parts.count == 2 {
                return .repository(owner: String(parts[0]), name: String(parts[1]))
            }
            return nil
        case "search":
            return .search(query: clean, name: name.isEmpty ? clean : name)
        case "code":
            return .code(query: clean, name: name.isEmpty ? clean : name)
        default:
            return nil
        }
    }
}
